a = input('digite algo: ')
print('o primitivo desse valor é: ', type(a))
print('Só tem espaços?', a.isspace())
print('E um numero?', a.isnumeric())
print('É alfabetico?: ',a.isalpha())
print('É alfanumerico?: ', a.isalnum())
print('Esta em maiuscula?: ', a.isupper())
print('Ésta em minusculo?: ', a.islower())
print('Esta capitalizada?: ', a.istitle())
#Este programa verifica o resultado digitado na variavel e informa se verdadeiro ou falso conforme o digitado